version: "3.9"
services:
  backend:
    build:
      context: ./backend
    environment:
      - DATABASE_URL=sqlite:////data/fittrack.db
      - CORS_ORIGINS=http://localhost:5173
    volumes:
      - ./backend:/app
      - ./data:/data
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    environment:
      - VITE_API_BASE=http://localhost:8000
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - backend
